[extension]
only-api = false # If true it removes commands and allow only to disguise via api

[disguises]
translate-player-names = true # If true it translates player names
translate-teams = false # If true it translates player teams to disguise